name: test-suite
on: [push, pull_request]
jobs:
  test-master:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: asr-hyper
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # (x64 or x86)
    - name: Install packages and run tests  
      run: |
        pip install pytest
        pip install --upgrade setuptools>=41.0.0
        git clone https://github.com/asreview/asreview.git
        pip install ./asreview[all]
        pip install ./asr-hyper
        pytest asr-hyper/tests
     
  #test-older:
    #name: pytest
    #runs-on: ubuntu-latest
    #strategy:
      #matrix:
        #asr_versions: ['0.7.2']
    #steps:
    #- uses: actions/checkout@v2
    #- uses: actions/setup-python@v1
      #with:
        #python-version: '3.6' # Version range or exact version of a Python version to use, using semvers version range syntax.
        #architecture: 'x64' # (x64 or x86)
    #- name: Install packages and run tests
      #run: |
        #pip install pytest
        #pip install --upgrade setuptools>=41.0.0
        #pip install asreview[all]==${{ matrix.asr_versions }}
        #pip install .
        #pytest tests
